sudo: required
language: java
jdk:
- oraclejdk8
script: mvn clean package
install: true
notifications:
  email:
    recipients:
    - ybrin.development@gmail.com
    - simon.artner@gmail.com
    on_success: change
    on_failure: always
  webhooks: https://api.kwstudios.org/travis/webhooks/versions
before_install:
- "./run_buildtools.sh"
cache:
  directories:
  - "$HOME/.m2"
before_deploy:
- ls
- cd target/
- ls
- cd ..
deploy:
  provider: gcs
  access_key_id: GOOGOORZ55TL3TFGHJHZ
  secret_access_key:
    secure: oOflhxSRCYyBVUSrD+icbkysWo22PskjUWzMwCLoUx6E3lKoDW+T/7Dbgx+AOQQLUz96o/C6L4mGTUQ+I4rSPMgo/iFbv3SQy6A+bC5SRS2/36b0Zrfq4TbWnGG9aH8lzXHm/4kNw9lL0nNYpdXV4f1tLgYAogS05H2SbbIlZGOxDQRWyHfEx4e5hi8gEch9lQNc/aAyC74TSCAY38+dlL8udGZWlRAvNVlEDTgqt6fqzCM8klIYNpVnm7ruKarGubLceAzRdhC6dC2qpIj0yI68MqZSTqgGl6tM3micY13qPQXG2SxnCwnNWZdwhbzJMk1czrLSzOM2pwkPjVA8scD26jBe9c9LEhkDpquDuWno2APsLeKtWIdfSe0Pdc4A7M6T+uUv0iDB2prITP7u0OBvmQz8fI28Du4gRfK2+v2ZvwxtrGyywUs6GC2N1Oq9Z45ZsiPuAD3O3iMtayRVbb8tSJhDpSlgS5p301FtusWVZn+ULnBBAi65jnmsFn6ljMIERw55wI20/gNfqRxs8dEh1XZFUBnPV08yz7Jq9zntUX80WbjxXjtQOe447WkIaVFBP0YleFVk2ghusSGn1Rvs4KruO42pygpzlI6t9/DttxW6rLxKtISi24r3PTZTXDu/TCCOHmaN/eyEBsv+ZHpAI25izWkXwdR8xbBOnxU=
  file_glob: true
  bucket: kwstudios-main-bucket
  local-dir: ${HOME}/build/${TRAVIS_REPO_SLUG}/target
  upload-dir: travis/kwringplugin/${TRAVIS_BUILD_NUMBER}
  skip_cleanup: true
  acl: public-read
  on:
    repo: KWStudios/KWRingPlugin
